name: Validate with hassfest

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "custom_components/groq/**"
      - "quality_scale.yaml"
      - "hacs.json"
      - ".github/workflows/hassfest.yml"
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "custom_components/groq/**"
      - "quality_scale.yaml"
      - "hacs.json"
      - ".github/workflows/hassfest.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - uses: home-assistant/actions/hassfest@master
