name: Validate

on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "custom_components/groq/manifest.json"
      - "hacs.json"
      - "README.md"
      - ".github/workflows/validate.yaml"
  pull_request:
    paths:
      - "custom_components/groq/manifest.json"
      - "hacs.json"
      - "README.md"
      - ".github/workflows/validate.yaml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: HACS validation
        uses: "hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa" # main
        with:
          category: "integration"
